#pragma once

// AUTO-GENERATED by scripts/gen_rules.py from stable ABI headers.
// Source: PyTorch stable ABI headers
// Do not edit manually. Re-run gen_rules.py to update.

#include <array>
#include <string_view>

namespace stable_abi {

// Include rules are structural and hand-maintained.
// The stable headers don't encode which unstable headers map to them.
struct IncludeRule {
    std::string_view old_path;
    std::string_view new_paths[5];
    bool remove_only;
};

inline constexpr std::array kIncludeRules = {
    IncludeRule{"torch/all.h", {"torch/csrc/stable/tensor.h", "torch/csrc/stable/ops.h", "torch/csrc/stable/accelerator.h", "torch/headeronly/core/ScalarType.h", "torch/csrc/stable/device.h"}, false},
    IncludeRule{"torch/torch.h", {"torch/csrc/stable/tensor.h", "torch/csrc/stable/ops.h", "torch/csrc/stable/accelerator.h", "torch/headeronly/core/ScalarType.h", "torch/csrc/stable/device.h"}, false},
    IncludeRule{"torch/extension.h", {"torch/csrc/stable/tensor.h", "torch/csrc/stable/ops.h", "torch/csrc/stable/accelerator.h", "torch/headeronly/core/ScalarType.h", "torch/csrc/stable/device.h"}, false},
    IncludeRule{"torch/cuda.h", {"torch/csrc/stable/accelerator.h", "cuda_runtime.h", "", "", ""}, false},
    IncludeRule{"torch/library.h", {"torch/csrc/stable/library.h", "", "", "", ""}, false},
    IncludeRule{"ATen/cuda/CUDAContext.h", {"torch/csrc/stable/accelerator.h", "cuda_runtime.h", "", "", ""}, false},
    IncludeRule{"c10/cuda/CUDAGuard.h", {"torch/csrc/stable/accelerator.h", "cuda_runtime.h", "", "", ""}, false},
    IncludeRule{"ATen/Dispatch.h", {"torch/headeronly/core/Dispatch.h", "torch/headeronly/core/Dispatch_v2.h", "", "", ""}, false},
    IncludeRule{"ATen/ATen.h", {"torch/csrc/stable/tensor.h", "torch/csrc/stable/ops.h", "torch/headeronly/core/ScalarType.h", "", ""}, false},
    IncludeRule{"ATen/cuda/Exceptions.h", {"torch/csrc/stable/macros.h", "", "", "", ""}, false},
    IncludeRule{"c10/cuda/CUDAException.h", {"torch/csrc/stable/macros.h", "", "", "", ""}, false},
    IncludeRule{"c10/cuda/CUDAStream.h", {"torch/csrc/stable/accelerator.h", "cuda_runtime.h", "", "", ""}, false},
    IncludeRule{"c10/util/Optional.h", {"", "", "", "", ""}, true},
};

struct TypeRule {
    std::string_view old_text;
    std::string_view new_text;
};

inline constexpr std::array kTypeRules = {
    TypeRule{"at::Tensor", "torch::stable::Tensor"},
    TypeRule{"torch::Tensor", "torch::stable::Tensor"},
    TypeRule{"c10::Device", "torch::stable::Device"},
    TypeRule{"at::Device", "torch::stable::Device"},
    TypeRule{"torch::Device", "torch::stable::Device"},
    TypeRule{"at::ScalarType", "torch::headeronly::ScalarType"},
    TypeRule{"c10::ScalarType", "torch::headeronly::ScalarType"},
    TypeRule{"torch::Dtype", "torch::headeronly::ScalarType"},
    TypeRule{"at::DeviceType", "torch::headeronly::DeviceType"},
    TypeRule{"c10::DeviceType", "torch::headeronly::DeviceType"},
    TypeRule{"at::Layout", "torch::headeronly::Layout"},
    TypeRule{"c10::Layout", "torch::headeronly::Layout"},
    TypeRule{"at::MemoryFormat", "torch::headeronly::MemoryFormat"},
    TypeRule{"c10::MemoryFormat", "torch::headeronly::MemoryFormat"},
    TypeRule{"at::Half", "torch::headeronly::Half"},
    TypeRule{"c10::Half", "torch::headeronly::Half"},
    TypeRule{"at::BFloat16", "torch::headeronly::BFloat16"},
    TypeRule{"c10::BFloat16", "torch::headeronly::BFloat16"},
    TypeRule{"c10::Float8_e4m3fn", "torch::headeronly::Float8_e4m3fn"},
    TypeRule{"c10::Float8_e4m3fnuz", "torch::headeronly::Float8_e4m3fnuz"},
    TypeRule{"c10::Float8_e5m2", "torch::headeronly::Float8_e5m2"},
    TypeRule{"c10::Float8_e5m2fnuz", "torch::headeronly::Float8_e5m2fnuz"},
    TypeRule{"c10::optional", "std::optional"},
    TypeRule{"c10::CppTypeToScalarType", "torch::headeronly::CppTypeToScalarType"},
    TypeRule{"torch::TensorOptions", ""},
    TypeRule{"at::TensorOptions", ""},
    TypeRule{"c10::TensorOptions", ""},
};

struct MacroRule {
    std::string_view old_name;
    std::string_view new_name;
    bool flag_only;
};

inline constexpr std::array kMacroRules = {
    MacroRule{"TORCH_CHECK", "STD_TORCH_CHECK", false},
    MacroRule{"TORCH_CHECK_NOT_IMPLEMENTED", "STD_TORCH_CHECK_NOT_IMPLEMENTED", false},
    // TORCH_CHECK_EQ/NE/LT/GT/GE/LE handled as special cases in PreprocessorCallbacks.cpp
    MacroRule{"TORCH_LIBRARY", "STABLE_TORCH_LIBRARY", false},
    MacroRule{"TORCH_LIBRARY_EXPAND", "STABLE_TORCH_LIBRARY_FRAGMENT", false},
    MacroRule{"TORCH_LIBRARY_IMPL", "STABLE_TORCH_LIBRARY_IMPL", false},
    MacroRule{"AT_DISPATCH_SWITCH", "THO_DISPATCH_SWITCH", false},
    MacroRule{"AT_DISPATCH_CASE", "THO_DISPATCH_CASE", false},
    MacroRule{"AT_DISPATCH_CASE_TYPE", "", true},
    MacroRule{"C10_CUDA_CHECK", "STD_CUDA_CHECK", false},
    MacroRule{"AT_CUDA_CHECK", "STD_CUDA_CHECK", false},
    MacroRule{"C10_CUDA_KERNEL_LAUNCH_CHECK", "STD_CUDA_KERNEL_LAUNCH_CHECK", false},
};

struct ScalarTypeShorthand {
    std::string_view old_text;
    std::string_view new_text;
};

inline constexpr std::array kScalarTypeShorthands = {
    ScalarTypeShorthand{"at::kByte", "torch::headeronly::ScalarType::Byte"},
    ScalarTypeShorthand{"torch::kByte", "torch::headeronly::ScalarType::Byte"},
    ScalarTypeShorthand{"at::kUInt8", "torch::headeronly::ScalarType::Byte"},
    ScalarTypeShorthand{"torch::kUInt8", "torch::headeronly::ScalarType::Byte"},
    ScalarTypeShorthand{"at::kChar", "torch::headeronly::ScalarType::Char"},
    ScalarTypeShorthand{"torch::kChar", "torch::headeronly::ScalarType::Char"},
    ScalarTypeShorthand{"at::kInt8", "torch::headeronly::ScalarType::Char"},
    ScalarTypeShorthand{"torch::kInt8", "torch::headeronly::ScalarType::Char"},
    ScalarTypeShorthand{"at::kShort", "torch::headeronly::ScalarType::Short"},
    ScalarTypeShorthand{"torch::kShort", "torch::headeronly::ScalarType::Short"},
    ScalarTypeShorthand{"at::kInt16", "torch::headeronly::ScalarType::Short"},
    ScalarTypeShorthand{"torch::kInt16", "torch::headeronly::ScalarType::Short"},
    ScalarTypeShorthand{"at::kInt", "torch::headeronly::ScalarType::Int"},
    ScalarTypeShorthand{"torch::kInt", "torch::headeronly::ScalarType::Int"},
    ScalarTypeShorthand{"at::kInt32", "torch::headeronly::ScalarType::Int"},
    ScalarTypeShorthand{"torch::kInt32", "torch::headeronly::ScalarType::Int"},
    ScalarTypeShorthand{"at::kLong", "torch::headeronly::ScalarType::Long"},
    ScalarTypeShorthand{"torch::kLong", "torch::headeronly::ScalarType::Long"},
    ScalarTypeShorthand{"at::kInt64", "torch::headeronly::ScalarType::Long"},
    ScalarTypeShorthand{"torch::kInt64", "torch::headeronly::ScalarType::Long"},
    ScalarTypeShorthand{"at::kHalf", "torch::headeronly::ScalarType::Half"},
    ScalarTypeShorthand{"torch::kHalf", "torch::headeronly::ScalarType::Half"},
    ScalarTypeShorthand{"at::kFloat16", "torch::headeronly::ScalarType::Half"},
    ScalarTypeShorthand{"torch::kFloat16", "torch::headeronly::ScalarType::Half"},
    ScalarTypeShorthand{"at::kFloat", "torch::headeronly::ScalarType::Float"},
    ScalarTypeShorthand{"torch::kFloat", "torch::headeronly::ScalarType::Float"},
    ScalarTypeShorthand{"at::kFloat32", "torch::headeronly::ScalarType::Float"},
    ScalarTypeShorthand{"torch::kFloat32", "torch::headeronly::ScalarType::Float"},
    ScalarTypeShorthand{"at::kDouble", "torch::headeronly::ScalarType::Double"},
    ScalarTypeShorthand{"torch::kDouble", "torch::headeronly::ScalarType::Double"},
    ScalarTypeShorthand{"at::kFloat64", "torch::headeronly::ScalarType::Double"},
    ScalarTypeShorthand{"torch::kFloat64", "torch::headeronly::ScalarType::Double"},
    ScalarTypeShorthand{"at::kComplexHalf", "torch::headeronly::ScalarType::ComplexHalf"},
    ScalarTypeShorthand{"torch::kComplexHalf", "torch::headeronly::ScalarType::ComplexHalf"},
    ScalarTypeShorthand{"at::kComplexFloat", "torch::headeronly::ScalarType::ComplexFloat"},
    ScalarTypeShorthand{"torch::kComplexFloat", "torch::headeronly::ScalarType::ComplexFloat"},
    ScalarTypeShorthand{"at::kComplexDouble", "torch::headeronly::ScalarType::ComplexDouble"},
    ScalarTypeShorthand{"torch::kComplexDouble", "torch::headeronly::ScalarType::ComplexDouble"},
    ScalarTypeShorthand{"at::kBool", "torch::headeronly::ScalarType::Bool"},
    ScalarTypeShorthand{"torch::kBool", "torch::headeronly::ScalarType::Bool"},
    ScalarTypeShorthand{"at::kBFloat16", "torch::headeronly::ScalarType::BFloat16"},
    ScalarTypeShorthand{"torch::kBFloat16", "torch::headeronly::ScalarType::BFloat16"},
    ScalarTypeShorthand{"at::kFloat8_e5m2", "torch::headeronly::ScalarType::Float8_e5m2"},
    ScalarTypeShorthand{"torch::kFloat8_e5m2", "torch::headeronly::ScalarType::Float8_e5m2"},
    ScalarTypeShorthand{"at::kFloat8_e4m3fn", "torch::headeronly::ScalarType::Float8_e4m3fn"},
    ScalarTypeShorthand{"torch::kFloat8_e4m3fn", "torch::headeronly::ScalarType::Float8_e4m3fn"},
    ScalarTypeShorthand{"at::kFloat8_e5m2fnuz", "torch::headeronly::ScalarType::Float8_e5m2fnuz"},
    ScalarTypeShorthand{"torch::kFloat8_e5m2fnuz", "torch::headeronly::ScalarType::Float8_e5m2fnuz"},
    ScalarTypeShorthand{"at::kFloat8_e4m3fnuz", "torch::headeronly::ScalarType::Float8_e4m3fnuz"},
    ScalarTypeShorthand{"torch::kFloat8_e4m3fnuz", "torch::headeronly::ScalarType::Float8_e4m3fnuz"},
    ScalarTypeShorthand{"at::kFloat8_e8m0fnu", "torch::headeronly::ScalarType::Float8_e8m0fnu"},
    ScalarTypeShorthand{"torch::kFloat8_e8m0fnu", "torch::headeronly::ScalarType::Float8_e8m0fnu"},
    ScalarTypeShorthand{"at::kFloat4_e2m1fn_x2", "torch::headeronly::ScalarType::Float4_e2m1fn_x2"},
    ScalarTypeShorthand{"torch::kFloat4_e2m1fn_x2", "torch::headeronly::ScalarType::Float4_e2m1fn_x2"},
};

struct DeviceTypeShorthand {
    std::string_view old_text;
    std::string_view new_text;
};

inline constexpr std::array kDeviceTypeShorthands = {
    DeviceTypeShorthand{"at::kCPU", "torch::headeronly::DeviceType::CPU"},
    DeviceTypeShorthand{"torch::kCPU", "torch::headeronly::DeviceType::CPU"},
    DeviceTypeShorthand{"at::kCUDA", "torch::headeronly::DeviceType::CUDA"},
    DeviceTypeShorthand{"torch::kCUDA", "torch::headeronly::DeviceType::CUDA"},
    DeviceTypeShorthand{"at::kMKLDNN", "torch::headeronly::DeviceType::MKLDNN"},
    DeviceTypeShorthand{"torch::kMKLDNN", "torch::headeronly::DeviceType::MKLDNN"},
    DeviceTypeShorthand{"at::kOPENGL", "torch::headeronly::DeviceType::OPENGL"},
    DeviceTypeShorthand{"torch::kOPENGL", "torch::headeronly::DeviceType::OPENGL"},
    DeviceTypeShorthand{"at::kOPENCL", "torch::headeronly::DeviceType::OPENCL"},
    DeviceTypeShorthand{"torch::kOPENCL", "torch::headeronly::DeviceType::OPENCL"},
    DeviceTypeShorthand{"at::kIDEEP", "torch::headeronly::DeviceType::IDEEP"},
    DeviceTypeShorthand{"torch::kIDEEP", "torch::headeronly::DeviceType::IDEEP"},
    DeviceTypeShorthand{"at::kHIP", "torch::headeronly::DeviceType::HIP"},
    DeviceTypeShorthand{"torch::kHIP", "torch::headeronly::DeviceType::HIP"},
    DeviceTypeShorthand{"at::kFPGA", "torch::headeronly::DeviceType::FPGA"},
    DeviceTypeShorthand{"torch::kFPGA", "torch::headeronly::DeviceType::FPGA"},
    DeviceTypeShorthand{"at::kMAIA", "torch::headeronly::DeviceType::MAIA"},
    DeviceTypeShorthand{"torch::kMAIA", "torch::headeronly::DeviceType::MAIA"},
    DeviceTypeShorthand{"at::kXLA", "torch::headeronly::DeviceType::XLA"},
    DeviceTypeShorthand{"torch::kXLA", "torch::headeronly::DeviceType::XLA"},
    DeviceTypeShorthand{"at::kVulkan", "torch::headeronly::DeviceType::Vulkan"},
    DeviceTypeShorthand{"torch::kVulkan", "torch::headeronly::DeviceType::Vulkan"},
    DeviceTypeShorthand{"at::kMetal", "torch::headeronly::DeviceType::Metal"},
    DeviceTypeShorthand{"torch::kMetal", "torch::headeronly::DeviceType::Metal"},
    DeviceTypeShorthand{"at::kXPU", "torch::headeronly::DeviceType::XPU"},
    DeviceTypeShorthand{"torch::kXPU", "torch::headeronly::DeviceType::XPU"},
    DeviceTypeShorthand{"at::kMPS", "torch::headeronly::DeviceType::MPS"},
    DeviceTypeShorthand{"torch::kMPS", "torch::headeronly::DeviceType::MPS"},
    DeviceTypeShorthand{"at::kMeta", "torch::headeronly::DeviceType::Meta"},
    DeviceTypeShorthand{"torch::kMeta", "torch::headeronly::DeviceType::Meta"},
    DeviceTypeShorthand{"at::kHPU", "torch::headeronly::DeviceType::HPU"},
    DeviceTypeShorthand{"torch::kHPU", "torch::headeronly::DeviceType::HPU"},
    DeviceTypeShorthand{"at::kVE", "torch::headeronly::DeviceType::VE"},
    DeviceTypeShorthand{"torch::kVE", "torch::headeronly::DeviceType::VE"},
    DeviceTypeShorthand{"at::kLazy", "torch::headeronly::DeviceType::Lazy"},
    DeviceTypeShorthand{"torch::kLazy", "torch::headeronly::DeviceType::Lazy"},
    DeviceTypeShorthand{"at::kIPU", "torch::headeronly::DeviceType::IPU"},
    DeviceTypeShorthand{"torch::kIPU", "torch::headeronly::DeviceType::IPU"},
    DeviceTypeShorthand{"at::kMTIA", "torch::headeronly::DeviceType::MTIA"},
    DeviceTypeShorthand{"torch::kMTIA", "torch::headeronly::DeviceType::MTIA"},
    DeviceTypeShorthand{"at::kPrivateUse1", "torch::headeronly::DeviceType::PrivateUse1"},
    DeviceTypeShorthand{"torch::kPrivateUse1", "torch::headeronly::DeviceType::PrivateUse1"},
};

struct MethodToFreeFunc {
    std::string_view method_name;
    std::string_view free_func;
};

inline constexpr std::array kMethodToFreeFuncRules = {
    MethodToFreeFunc{"empty_like", "torch::stable::empty_like"},
    MethodToFreeFunc{"fill_", "torch::stable::fill_"},
    MethodToFreeFunc{"narrow", "torch::stable::narrow"},
    MethodToFreeFunc{"new_empty", "torch::stable::new_empty"},
    MethodToFreeFunc{"new_zeros", "torch::stable::new_zeros"},
    MethodToFreeFunc{"pad", "torch::stable::pad"},
    MethodToFreeFunc{"amax", "torch::stable::amax"},
    MethodToFreeFunc{"transpose", "torch::stable::transpose"},
    MethodToFreeFunc{"zero_", "torch::stable::zero_"},
    MethodToFreeFunc{"copy_", "torch::stable::copy_"},
    MethodToFreeFunc{"clone", "torch::stable::clone"},
    MethodToFreeFunc{"flatten", "torch::stable::flatten"},
    MethodToFreeFunc{"unsqueeze", "torch::stable::unsqueeze"},
    MethodToFreeFunc{"squeeze", "torch::stable::squeeze"},
    MethodToFreeFunc{"select", "torch::stable::select"},
    MethodToFreeFunc{"matmul", "torch::stable::matmul"},
    MethodToFreeFunc{"reshape", "torch::stable::reshape"},
    MethodToFreeFunc{"view", "torch::stable::view"},
    MethodToFreeFunc{"to", "torch::stable::to"},
    MethodToFreeFunc{"contiguous", "torch::stable::contiguous"},
    MethodToFreeFunc{"sum", "torch::stable::sum"},
    MethodToFreeFunc{"subtract", "torch::stable::subtract"},
};

struct MethodRenameRule {
    std::string_view old_name;
    std::string_view new_name;
};

inline constexpr std::array kMethodRenameRules = {
    MethodRenameRule{"dtype", "scalar_type"},
    MethodRenameRule{"itemsize", "element_size"},
};

struct FreeFuncRule {
    std::string_view old_qualified;
    std::string_view new_qualified;
};

inline constexpr std::array kFreeFuncRules = {
    FreeFuncRule{"torch::parallel_for", "torch::stable::parallel_for"},
    FreeFuncRule{"at::parallel_for", "torch::stable::parallel_for"},
    FreeFuncRule{"torch::get_num_threads", "torch::stable::get_num_threads"},
    FreeFuncRule{"at::get_num_threads", "torch::stable::get_num_threads"},
    FreeFuncRule{"torch::empty", "torch::stable::empty"},
    FreeFuncRule{"at::empty", "torch::stable::empty"},
    FreeFuncRule{"torch::from_blob", "torch::stable::from_blob"},
    FreeFuncRule{"at::from_blob", "torch::stable::from_blob"},
    FreeFuncRule{"torch::full", "torch::stable::full"},
    FreeFuncRule{"at::full", "torch::stable::full"},
    FreeFuncRule{"torch::zeros", "torch::stable::full"},
    FreeFuncRule{"at::zeros", "torch::stable::full"},
    FreeFuncRule{"torch::empty_like", "torch::stable::empty_like"},
    FreeFuncRule{"at::empty_like", "torch::stable::empty_like"},
    FreeFuncRule{"torch::clone", "torch::stable::clone"},
    FreeFuncRule{"at::clone", "torch::stable::clone"},
    FreeFuncRule{"torch::transpose", "torch::stable::transpose"},
    FreeFuncRule{"at::transpose", "torch::stable::transpose"},
    FreeFuncRule{"torch::flatten", "torch::stable::flatten"},
    FreeFuncRule{"at::flatten", "torch::stable::flatten"},
    FreeFuncRule{"torch::squeeze", "torch::stable::squeeze"},
    FreeFuncRule{"at::squeeze", "torch::stable::squeeze"},
    FreeFuncRule{"torch::unsqueeze", "torch::stable::unsqueeze"},
    FreeFuncRule{"at::unsqueeze", "torch::stable::unsqueeze"},
    FreeFuncRule{"torch::matmul", "torch::stable::matmul"},
    FreeFuncRule{"at::matmul", "torch::stable::matmul"},
    FreeFuncRule{"torch::contiguous", "torch::stable::contiguous"},
    FreeFuncRule{"at::contiguous", "torch::stable::contiguous"},
    FreeFuncRule{"torch::reshape", "torch::stable::reshape"},
    FreeFuncRule{"at::reshape", "torch::stable::reshape"},
    FreeFuncRule{"torch::select", "torch::stable::select"},
    FreeFuncRule{"at::select", "torch::stable::select"},
    FreeFuncRule{"torch::narrow", "torch::stable::narrow"},
    FreeFuncRule{"at::narrow", "torch::stable::narrow"},
    FreeFuncRule{"torch::sum", "torch::stable::sum"},
    FreeFuncRule{"at::sum", "torch::stable::sum"},
    FreeFuncRule{"torch::pad", "torch::stable::pad"},
    FreeFuncRule{"at::pad", "torch::stable::pad"},
    FreeFuncRule{"torch::amax", "torch::stable::amax"},
    FreeFuncRule{"at::amax", "torch::stable::amax"},
    FreeFuncRule{"torch::zero_", "torch::stable::zero_"},
    FreeFuncRule{"at::zero_", "torch::stable::zero_"},
    FreeFuncRule{"torch::fill_", "torch::stable::fill_"},
    FreeFuncRule{"at::fill_", "torch::stable::fill_"},
    FreeFuncRule{"torch::copy_", "torch::stable::copy_"},
    FreeFuncRule{"at::copy_", "torch::stable::copy_"},
};

} // namespace stable_abi
